### ISSUE TITLE
Troublw drawing region maps (Windows)

### ISSUE THREAD

**Issue by amroco** [SeaAroundUs/rseaaroundus#1]
Hi there!
Awesome product! 
I am however getting the following error:

> # get map of all eez regions
> # NOTE: users on Windows have had some issues drawing region maps
> regionmap("eez")
Error in ogrListLayers(url) : Cannot open data source

Any suggestions?
Cheers,
Ames

**Comment by EvilScott** [comment]
@amroco Are you using Windows?

**Comment by amroco** [comment]
I am, this is my work computer at Sea Around Us :)
Everything else is great however!

**Comment by EvilScott** [comment]
We can leave this open for now, but I don't now if it will be able to be addressed. I reached out to someone who is a little bit more experienced with rgdal and R than me so we'll see what happens.
