### ISSUE TITLE
Taxonomic information for all taxa?

### ISSUE THREAD

**Issue by jafflerbach** [SeaAroundUs/rseaaroundus#5]
Does SAUP have taxonomic information for all Taxa? Something that provides taxonomic information from species to class for all taxa? something like:

| Taxon name   | Genus  | Species | Family       | Order       | Class          |
|--------------|--------|---------|--------------|-------------|----------------|
| Gadus morhua | Gadus  | morhua  | Gadidae      | Perciformes | Actinopterygii |
| Carangidae   |    NA    |    NA     | Carangidae   | Perciformes | Actinopterygii |
| Octopodidae  |  NA      |  NA       | Octopodidae  | Octopoda    | Cephalopoda    |
| Pampus       | Pampus | NA      | Stromateidae | Perciformes | Actinopterygii |

**Comment by EvilScott** [comment]
I'm providing all the data that is accessible in the SAUP database. You can always check out [Fishbase](http://www.fishbase.org/) for more data 😄

**Comment by jcvdav** [comment]
Hey Jamie,

In the amazing `rfishbase` package, you can use `sp_list <- rfishbase::load_taxa()` to load a quite complete list of species (33,104 obs) with their taxonomic information all the way up to Family. From there you can either subset what you need, or perform a join.

Also, it may be worth looking into `taxize`, another great package with many interesting functions for working with taconomic information.

**Comment by jafflerbach** [comment]
Ah great thanks for that tip. I'm also exploring the [myTAI](https://cran.r-project.org/web/packages/myTAI/vignettes/Introduction.html) package (uses taxize) as it outputs the info I need nicely. Seems like I'll be able to get what I need with these options.
